services:
  bika-web:
    image: ghcr.io/mogvl/bika:latest
    container_name: bika-web
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/bika:/data/downloads
      - /volume1/docker/bika:/data/config
      - /volume1/docker/bika/cache:/data/cache
    restart: unless-stopped
